spaces = ' ' * 25
print('%s 12 Butts wynd' % spaces)
print('%s Twinklebottom Heath' % spaces)
print('%s west snoring' % spaces)
print()
print()
print('Dear sir')
print()
print('I wish to repport that tiles are missing from the')
print('outside toulet foof.')
print('Ithink it was bad wind the other night that blew then away')
print()
print('Regards')
print('Malcolm Dithering')
